### ISSUE TITLE
Default images for social medias.

### ISSUE THREAD

**Issue by razonyang** [hugomods/seo#14]

**Comment by razonyang** [comment]
Already implemented by internal template, just use site's `images` parameter.

```toml
[params]
images = ["feature.jpg"]
```
